version: '3'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:10.6
    environment:
      POSTGRES_USER:
        tstnwadmin
      POSTGRES_PASS:
        tstnwadminpass
      POSTGRES_DB:
        tstnwdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  python:
    image: python:3.6.8
    volumes:
      - ../TSTNW:/TSTNW
    command: >
      bash -c "cd /TSTNW && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
