version: '3'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:10.6
    hostname: db
    environment:
      POSTGRES_USER:
        tstnwadmin
      POSTGRES_PASS:
        tstnwadminpass
      POSTGRES_DB:
        tstnwdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    # sudo docker exec -it [ID Contenedor de Docker] python /TSTNW/manage.py createsuperuser
    # sudo docker-compose run tstnwapp bash
  tstnwapp:
    image: python:3.6.8
    hostname: tstnwapp
    volumes:
      - ../TSTNW:/TSTNW
    expose:
      - "8000"
    command: >
      bash -c "cd /TSTNW && pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind :80 TSTNW.wsgi"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.13
    ports: # <-- Cambiar a 80:80 luego en prod
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      #Corregit esto para prod porque no va a coger los static de un virtualenv en producción
    depends_on:
      - tstnwapp
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  nginx_network:
    driver: bridge
