version: '3'
volumes:
  pgdata:

services:
  postgres:
    build: ./config//Docker_db/
    hostname: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  tstnwapp:
    image: python:3.6.8
    hostname: tstnwapp
    volumes:
      - ../TSTNW:/TSTNW
    command: >
      bash -c "cd /TSTNW && pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && gunicorn --bind :80 TSTNW.wsgi"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.13
    ports: # <-- Cambiar a 80:80 luego en prod
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - tstnwapp

networks:
  nginx_network:
    driver: bridge
