# Generated by Django 2.2.3 on 2019-07-23 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opinion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateField(default=datetime.date(2019, 7, 23))),
                ('pre1', models.CharField(max_length=296)),
                ('pre2', models.TextField(blank=True, max_length=296, null=True)),
                ('pre3', models.IntegerField(choices=[('SI', 'A FAVOR'), ('NO', 'ENCONTRA')])),
            ],
        ),
    ]
