# Generated by Django 2.2.3 on 2019-07-23 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 8, 35, 20, 175555, tzinfo=utc)),
        ),
    ]
