# Generated by Django 2.2.3 on 2019-07-23 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_auto_20190723_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2019, 7, 23, 8, 38, 24, 511319)),
        ),
    ]
