# Generated by Django 2.2.3 on 2019-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0003_auto_20190723_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
