# Generated by Django 2.2.3 on 2019-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0004_auto_20190723_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='pre3',
            field=models.CharField(choices=[('A FAVOR', 'A FAVOR'), ('ENCONTRA', 'ENCONTRA')], max_length=10),
        ),
    ]
