# Generated by Django 2.2.3 on 2019-07-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0005_auto_20190723_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='pre3',
            field=models.TextField(choices=[('A FAVOR', 'A FAVOR'), ('ENCONTRA', 'ENCONTRA')], max_length=20),
        ),
    ]
