# Generated by Django 2.2.3 on 2019-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0008_auto_20190723_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['pre3'], 'verbose_name': 'Opinion', 'verbose_name_plural': 'Opiniones'},
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pre1',
            field=models.TextField(max_length=296),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pre3',
            field=models.CharField(choices=[('A FAVOR', 'A FAVOR'), ('ENCONTRA', 'ENCONTRA')], max_length=15),
        ),
    ]
